version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.0  # Specify the Python version you are using
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt  # Install Flask

  build:
    commands:
      - echo "Building the application"
      - echo "No specific build commands needed for this app"

  post_build:
    commands:
      - echo "Starting Flask application"
      - nohup python application.py &  # Start the Flask app in the background

artifacts:
  files:
    - '**/*'  # Include all files in the output
  discard-paths: no
  base-directory: /  # Use the root directory for the app

frontend:
  phases:
    preBuild:
      commands:
        - echo Preparing the frontend...
    build:
      commands:
        - echo Building the frontend...
  artifacts:
    baseDirectory: /  # Adjust according to your frontend folder
    files:
      - '**/*' 

# Start Gunicorn as the production server
run-as:
  commands:
    - echo "Starting Gunicorn server..."
    - gunicorn --bind 0.0.0.0:8080 application:app  # Bind to the port and serve the Flask app